package com.fpltn.entities;
// Generated Apr 25, 2023, 2:09:08 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cartlist generated by hbm2java
 */
@Entity
@Table(name = "cartlist", catalog = "dbbh")
public class Cartlist implements java.io.Serializable {

	private Integer idcart;
	private Sanpham sanpham;
	private User user;
	private Integer soluong;
	private Double tongtien;
	private Boolean trangthai;

	public Cartlist() {
	}

	public Cartlist(Sanpham sanpham, User user, Integer soluong, Double tongtien, Boolean trangthai) {
		this.sanpham = sanpham;
		this.user = user;
		this.soluong = soluong;
		this.tongtien = tongtien;
		this.trangthai = trangthai;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcart", unique = true, nullable = false)
	public Integer getIdcart() {
		return this.idcart;
	}

	public void setIdcart(Integer idcart) {
		this.idcart = idcart;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsp")
	public Sanpham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(Sanpham sanpham) {
		this.sanpham = sanpham;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "soluong")
	public Integer getSoluong() {
		return this.soluong;
	}

	public void setSoluong(Integer soluong) {
		this.soluong = soluong;
	}

	@Column(name = "tongtien", precision = 22, scale = 0)
	public Double getTongtien() {
		return this.tongtien;
	}

	public void setTongtien(Double tongtien) {
		this.tongtien = tongtien;
	}

	@Column(name = "trangthai")
	public Boolean getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Boolean trangthai) {
		this.trangthai = trangthai;
	}

}
