package com.fpltn.entities;
// Generated Apr 25, 2023, 2:09:08 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Danhmuc generated by hbm2java
 */
@Entity
@Table(name = "danhmuc", catalog = "dbbh")
public class Danhmuc implements java.io.Serializable {

	private Integer iddm;
	private String tendm;
	private String mota;
	private Set<Sanpham> sanphams = new HashSet<Sanpham>(0);

	public Danhmuc() {
	}

	public Danhmuc(String tendm) {
		this.tendm = tendm;
	}

	public Danhmuc(String tendm, String mota, Set<Sanpham> sanphams) {
		this.tendm = tendm;
		this.mota = mota;
		this.sanphams = sanphams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddm", unique = true, nullable = false)
	public Integer getIddm() {
		return this.iddm;
	}

	public void setIddm(Integer iddm) {
		this.iddm = iddm;
	}

	@Column(name = "tendm", nullable = false, length = 45)
	public String getTendm() {
		return this.tendm;
	}

	public void setTendm(String tendm) {
		this.tendm = tendm;
	}

	@Column(name = "mota", length = 45)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "danhmuc")
	public Set<Sanpham> getSanphams() {
		return this.sanphams;
	}

	public void setSanphams(Set<Sanpham> sanphams) {
		this.sanphams = sanphams;
	}

}
