package com.fpltn.entities;
// Generated Apr 25, 2023, 2:09:08 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sanpham generated by hbm2java
 */
@Entity
@Table(name = "sanpham", catalog = "dbbh", uniqueConstraints = @UniqueConstraint(columnNames = "masp"))
public class Sanpham implements java.io.Serializable {

	private Integer id;
	private Danhmuc danhmuc;
	private String masp;
	private String tensp;
	private Double giaban;
	private String motangan;
	private String hinhanh;
	private Boolean trangthai;
	private String ghichu;
	private Integer soluong;
	private Integer daban;
	private Set<Cartlist> cartlists = new HashSet<Cartlist>(0);

	public Sanpham() {
	}

	public Sanpham(Danhmuc danhmuc, String masp, String tensp, Double giaban, String motangan, String hinhanh,
			Boolean trangthai, String ghichu, Integer soluong, Integer daban, Set<Cartlist> cartlists) {
		this.danhmuc = danhmuc;
		this.masp = masp;
		this.tensp = tensp;
		this.giaban = giaban;
		this.motangan = motangan;
		this.hinhanh = hinhanh;
		this.trangthai = trangthai;
		this.ghichu = ghichu;
		this.soluong = soluong;
		this.daban = daban;
		this.cartlists = cartlists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddanhmuc")
	public Danhmuc getDanhmuc() {
		return this.danhmuc;
	}

	public void setDanhmuc(Danhmuc danhmuc) {
		this.danhmuc = danhmuc;
	}

	@Column(name = "masp", unique = true, length = 45)
	public String getMasp() {
		return this.masp;
	}

	public void setMasp(String masp) {
		this.masp = masp;
	}

	@Column(name = "tensp", length = 45)
	public String getTensp() {
		return this.tensp;
	}

	public void setTensp(String tensp) {
		this.tensp = tensp;
	}

	@Column(name = "giaban", precision = 22, scale = 0)
	public Double getGiaban() {
		return this.giaban;
	}

	public void setGiaban(Double giaban) {
		this.giaban = giaban;
	}

	@Column(name = "motangan", length = 160)
	public String getMotangan() {
		return this.motangan;
	}

	public void setMotangan(String motangan) {
		this.motangan = motangan;
	}

	@Column(name = "hinhanh")
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	@Column(name = "trangthai")
	public Boolean getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Boolean trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "ghichu")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@Column(name = "soluong")
	public Integer getSoluong() {
		return this.soluong;
	}

	public void setSoluong(Integer soluong) {
		this.soluong = soluong;
	}

	@Column(name = "daban")
	public Integer getDaban() {
		return this.daban;
	}

	public void setDaban(Integer daban) {
		this.daban = daban;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanpham")
	public Set<Cartlist> getCartlists() {
		return this.cartlists;
	}

	public void setCartlists(Set<Cartlist> cartlists) {
		this.cartlists = cartlists;
	}

}
